name: barber_link
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2 # Ajusta según tu versión de Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  google_fonts: ^6.2.1
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.5.0
  provider: ^6.1.4
  flutter_stripe: ^11.5.0
  dio: ^5.8.0+1
  google_sign_in: ^6.3.0
  
  flutter_easy_recaptcha_v2: ^0.1.0
  flutter_inappwebview: ^6.1.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/bigote.png
    - assets/Icons/google.png
    - assets/Icons/FaceebookLogo.png
    - assets/Images/corte.png
    - assets/Images/sombrero.png
    - assets/Images/clasico.png