// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-8FUmgC4n5BcVSs0F07uVHf-G9vi7voo',
    appId: '1:379548823363:web:d1ba0502b23c4b925cc9f6',
    messagingSenderId: '379548823363',
    projectId: 'barberlink-a4f23',
    authDomain: 'barberlink-a4f23.firebaseapp.com',
    storageBucket: 'barberlink-a4f23.firebasestorage.app',
    measurementId: 'G-CBSR2L5L4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgYJ7CfTr18Gzfd5wgrgTe26of71x-bzY',
    appId: '1:379548823363:android:6d3c9f5f64465bad5cc9f6',
    messagingSenderId: '379548823363',
    projectId: 'barberlink-a4f23',
    storageBucket: 'barberlink-a4f23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT5YDLi20JxKLoaNu-EaCGdN5CQEz1xm8',
    appId: '1:379548823363:ios:a8f79f19be1877785cc9f6',
    messagingSenderId: '379548823363',
    projectId: 'barberlink-a4f23',
    storageBucket: 'barberlink-a4f23.firebasestorage.app',
    iosBundleId: 'com.example.barberLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT5YDLi20JxKLoaNu-EaCGdN5CQEz1xm8',
    appId: '1:379548823363:ios:a8f79f19be1877785cc9f6',
    messagingSenderId: '379548823363',
    projectId: 'barberlink-a4f23',
    storageBucket: 'barberlink-a4f23.firebasestorage.app',
    iosBundleId: 'com.example.barberLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-8FUmgC4n5BcVSs0F07uVHf-G9vi7voo',
    appId: '1:379548823363:web:bfbf341d562976e45cc9f6',
    messagingSenderId: '379548823363',
    projectId: 'barberlink-a4f23',
    authDomain: 'barberlink-a4f23.firebaseapp.com',
    storageBucket: 'barberlink-a4f23.firebasestorage.app',
    measurementId: 'G-0J361DWTQW',
  );
}
